### ISSUE TITLE
rmt_UnbindOpenGL blocks indefinitely

### ISSUE THREAD

**Issue by graphitemaster** [Celtoys/Remotery#112]
after creating Remotery and OpenGL context on the same thread, and issuing `rmt_BindOpenGL` on the same thread. Placing a call to `rmt_UnbindOpenGL` before shutting down Remotery blocks indefnintely in `Remotery_BlockingDeleteSampleTree` because of the following code:

```
            // Wait around until the Remotery server thread has sent all sample trees
            // of this type to the client
            while (sample_tree->allocator->nb_inuse > 1)
                msSleep(1);
```

The only way to get the application to close is to load up the Remotery web console in a webbrowser and wait for all the events to be sent to it. Is there a way to "jump the gun" and terminate the application even if there is samples pending?

**Comment by graphitemaster** [comment]
Adding the following in `Remotery_FlushMessageQueue` fixes the problem

```
        // NOTE(daleweiler): added this
        if ( rmtMessageQueue_IsEmpty( rmt->mq_to_rmt_thread ) )
            break;
```

Then instead of breaking when message is NULL, continue (skip it) instead

**Comment by graphitemaster** [comment]
Actually that does not fix it, it just takes a long time to release the queue

**Comment by graphitemaster** [comment]
It's just confusing why it's not terminating immediately

**Comment by dwilliamson** [comment]
So the Remotery thread owns the sample memory once your profiled thread hands it over. Once it's done its work it hands it back to your thread to release the queries on the thread that they were created. The queries don't *have* to follow this path, the code is just a lot simpler to write that way.

I'm presuming the main Remotery thread loop has exited as per your request and the server is looping in `Remotery_FlushMessageQueue`

Can you verify that?

**Comment by graphitemaster** [comment]
Looks like it

**Comment by graphitemaster** [comment]
It also looks like the text in the samples has disappeared in the web viewer as well, almost magically, kind of strange

**Comment by dwilliamson** [comment]
I think I'd like to solve why it's not shutting down when no client is running, and then hopefully the rest will fall out from that.

Does it go into the same infinite loop with no viewer running?

**Comment by graphitemaster** [comment]
It terminates when the viewer is running, it's when it's not running that is gets stuck in an infinite loop

**Comment by dwilliamson** [comment]
That's confusing; when the main thread loop exits, there's no further interaction with the web client.

In `Remotery_FlushMessageQueue` can you verify that `rmt->mq_to_rmt_thread->write_pos` isn't advancing?

**Comment by graphitemaster** [comment]
`rmt->mq_to_rmt_thread->write_pos` is not advancing, and `rmt->mq_to_rmt_thread->read_pos` is decrementing (it's huge mind you ....)

**Comment by dwilliamson** [comment]
what's `write_pos-read_pos`?

**Comment by graphitemaster** [comment]
Constantly decrementing, currently `12816`, letting it run long enough (with the remotery viewer open) it eventually converges to zero (but it takes an awful long time ...) Without the viewer opened `rmt->mq_to_rmt->thread->read_pos` never decrements, actually it appears that `Remotery_FlushMessageQueue` is never actually called.

**Comment by graphitemaster** [comment]
Trying to terminate the thread by sending it a signal (SIGINT) just blocks in `pthread_join` (from Remotery_Destructor) indefinitely as well

**Comment by dwilliamson** [comment]
Hang on, is `write_pos-read_pos` decrementing or is `read_pos` decrementing? `read_pos` should only ever increment.

**Comment by graphitemaster** [comment]
it increments with viewer open (and connection not paused), with the viewer closed it never increments

**Comment by graphitemaster** [comment]
`Remotery_FlushMessageQueue` is never called when the viewer is closed and the instance is destroyed, thus I can't tell you the result of `write_pos-read_pos`

**Comment by dwilliamson** [comment]
Right, it's the never closed bit I'm interested in. Can you interrupt the thread and see where it's looping when the viewer is closed?

**Comment by graphitemaster** [comment]
It loops in `Remotery_BlockingDeleteSampleTree`

**Comment by graphitemaster** [comment]
(after calling `rmt_UnbindOpenGL`)

**Comment by dwilliamson** [comment]
I mean the Remotery thread. You have 2 active; one is the thread you're pushing samples from, the second one is the Remotery communication thread that is created for you.

**Comment by graphitemaster** [comment]
in the Remotery thread it blocks in `Remotery_ThreadMain`

**Comment by graphitemaster** [comment]
I guess `request_exit` never get's set `RMT_FALSE`, that is set when the thread is requested to be shut down, but that never happens unless you destroy the instance, but I can't issue that until `rmt_UnbindOpenGL` returns.

**Comment by graphitemaster** [comment]
(documentation says to unbind before destroying the instance)

**Comment by dwilliamson** [comment]
Yup, that's what it's looking like...

**Comment by graphitemaster** [comment]
Why would `rmt_UnbindOpenGL` not terminate (`nb_inuse` not converging to zero)?

**Comment by dwilliamson** [comment]
It's waiting for the Remotery thread to send the OpenGL sample data to the viewer before the samples can be released.

**Comment by dwilliamson** [comment]
Can you try commenting out https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L4450 and see what happens?

**Comment by graphitemaster** [comment]
(and the return proceeding it?)

**Comment by dwilliamson** [comment]
yes

**Comment by graphitemaster** [comment]
Same behavior

**Comment by dwilliamson** [comment]
That should work; no idea what's going on. I have an OpenGL project tomorrow I can try and repro this on so will see what I can do (although it's the same path all the other GPU samplers follow).

**Comment by graphitemaster** [comment]
Actually wait a second, something really strange is happening here; eventually the queue becomes empty and peek on the queue returns `NULL`, and the `FlushMessageQueue` breaks out. Something else is dead locking now.

**Comment by dwilliamson** [comment]
yeah, commenting it out is not actually the solution but it should no longer block in the thread main. It would very slowly drain the queue and demonstrate that I have an understanding of the problem.

**Comment by graphitemaster** [comment]
The socket you setup for the communication, do you set the appropriate options for it not to issue a signal. Specifically `SO_KEEPALIVE`? It's allowed to issue a `SIGPIPE` which is not thread safe on POSIX.

**Comment by graphitemaster** [comment]
er, SO_NOSIGPIPE

**Comment by graphitemaster** [comment]
ah you do, that's not an issue

**Comment by dwilliamson** [comment]
Not sure, that code was written by one of the contributors. See 2257.

**Comment by graphitemaster** [comment]
There is a 50 second timeout for sending the sample tree?

**Comment by dwilliamson** [comment]
That's probably not wise...

**Comment by graphitemaster** [comment]
Okay combination of that commenting out, changing the timeout for the sample tree from 50 seconds to 5 seconds seems to fix the problems ...

**Comment by dwilliamson** [comment]
That should be something < 10ms as failure to send will not lose data

**Comment by dwilliamson** [comment]
OK, good... that means the unbind logic needs some rethinking for when there's no connection

**Comment by graphitemaster** [comment]
Suppose you could just set an atomic variable when there is no connection from unbind and check for it during drain to early out and just consume the entire queue and free the sample tree

**Comment by dwilliamson** [comment]
Potentially! This late at night I don't trust any decisions my brain makes so will follow up with this soon. Meanwhile, the timeout for sample tree sending is certainly a good bug find.

**Comment by dwilliamson** [comment]
Fixed on latest.

**Comment by marcakafoddex** [comment]
I'm still seeing this problem on the master branch. The thread that is doing the rendering hangs indefinitely on rmt_UnbindOpenGL

**Comment by marcakafoddex** [comment]
I have to mention that I'm seeing other weird behavior in Remotery. If I don't sample anything at all, just call rmt_CreateGlobalInstance at startup, and rmt_DestroyGlobalInstance at shutdown, I'm getting an assert error in ObjectAllocator_Destructor on assert(allocator->nb_inuse == 0);

**Comment by dwilliamson** [comment]
What's your callstack when it hangs?

Do you by any chance have another thread still submitting OpenGL samples while it's shutting down?

**Comment by marcakafoddex** [comment]
It's looping forever on the following, because IsEmpty never returns true:

        // Stall waiting for the OpenGL queue to empty into the Remotery queue
        while (!rmtMessageQueue_IsEmpty(opengl->mq_to_opengl_main))
            UpdateOpenGLFrame();

- There are no threads of mine calling any rmt_XXX functions while this is happening
- Only UpdateOpenGLFrame() itself and the Remotery thread itself are calling rmt_XXX functions
- The queue->write_pos and queue->read_pos values never change once it gets stuck in this loop
- The difference between the two values is always exactly 48 

Hope this helps.

**Comment by dwilliamson** [comment]
> EDIT: I think THIS particular issue is a build issue. When I built remotery into a dll shutdown crashes, when i build my project statically it works. So I blame this on my build system.

Remotery uses a global variable to keep the public API clean. When you call `rmt_CreateGlobalInstance` from your main program you must propagate the returned `Remotery` object to any DLLs using `rmt_SetGlobalInstance`.

**Comment by dwilliamson** [comment]
> It's looping forever on the following, because IsEmpty never returns true:

This can only be an OpenGL issue... maybe. Couple more questions:

* Have you destroyed your OpenGL context or shut it down in any way before this point?
* Have you destroyed Remotery itself?

**Comment by marcakafoddex** [comment]
> > It's looping forever on the following, because IsEmpty never returns true:
> 
> This can only be an OpenGL issue... maybe. Couple more questions:
> 
> * Have you destroyed your OpenGL context or shut it down in any way before this point?
I had called glfwMakeContextCurrent already when I called rmt_UnbindOpenGL, swapping the calls works a lot better!

> * Have you destroyed Remotery itself?
Nope I hadn't

So, I'm getting a lot further now. But it's still not working a 100%. When I shutdown my app and call rmt_UnbindOpenGL, it now crashes a few calls into FlattenSampleTree:

>	!FlattenSampleTree(Sample * sample, unsigned int * nb_samples) Line 4237	C
 	!FlattenSampleTree(Sample * sample, unsigned int * nb_samples) Line 4242	C
 	!FreeSampleTree(Sample * sample, ObjectAllocator * allocator) Line 4260	C
 	!FreePendingSampleTrees(Remotery * rmt, SampleType sample_type, Buffer * flush_samples) Line 5520	C
 	!_rmt_UnbindOpenGL() Line 6891	C

**Comment by dwilliamson** [comment]
OK this crash is new. Can you open a new issue with additional exception information, as well?
